#!/usr/bin/env rake

$: << "."

require 'socket'
require 'dynasty'

task :default => :server

task :server do
  leader, descriptors = Dynasty.server

  select_timeout = 0.001 
  selectable_sockets = [leader]

  puts selectable_sockets.inspect

  ruling = true

  if descriptors.empty?
    puts :making
    descriptors = []
    descriptors << TCPServer.new("localhost", 12345)
    descriptors << TCPServer.new("localhost", 12346)
  end

  puts "!!!!"
  puts leader.inspect
  puts leader.closed?
  puts "!!!!"

  while ruling
    readable, writable, errored = IO.select(selectable_sockets, nil, nil, select_timeout)
    $stdout.write(".")

    readable && readable.each do |needs_reading|
      puts :read, needs_reading
      case needs_reading
        when leader
          ruling = Dynasty.rule(leader, descriptors)
      end

      puts :readed, needs_reading.rean_nonblock(1014)
    end

    writable && writable.each do |needs_writing|
      puts :write, needs_writing
    end
  end

  puts :done

end
